'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import AppShell from '../../components/AppShell';
import {API,authHeaders,currentStoreId,money} from '../api';

const empty={name:'',barcode:'',cost_price:'',sale_price:'',stock_qty:'',min_stock_qty:'5'};
export default function Products(){
 const r=useRouter(); const [items,setItems]=useState([]); const [form,setForm]=useState(empty); const [q,setQ]=useState(''); const [err,setErr]=useState(''); const [open,setOpen]=useState(false);
 async function load(search=''){const store=currentStoreId();if(!store){r.push('/dashboard');return} const res=await fetch(`${API}/stores/${store}/products${search?`?q=${encodeURIComponent(search)}`:''}`,{headers:authHeaders()}); if(res.status===401){r.push('/login');return} const d=await res.json(); if(res.ok)setItems(d); else setErr(d.detail||'Xatolik')}
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();setErr('');const store=currentStoreId();const body={...form,cost_price:Number(form.cost_price),sale_price:Number(form.sale_price),stock_qty:Number(form.stock_qty),min_stock_qty:Number(form.min_stock_qty),barcode:form.barcode||null};const res=await fetch(`${API}/stores/${store}/products`,{method:'POST',headers:authHeaders(true),body:JSON.stringify(body)});const d=await res.json();if(!res.ok){setErr(d.detail||'Mahsulot saqlanmadi');return}setForm(empty);setOpen(false);load(q)}
 return <AppShell title="Mahsulotlar" subtitle={`${items.length} ta mahsulot`} action={<button className="btn btnAccent" onClick={()=>setOpen(true)}>+ Mahsulot</button>}>
  <div className="toolbar"><input className="search" value={q} onChange={e=>{setQ(e.target.value);load(e.target.value)}} placeholder="Nomi yoki barcode bo‘yicha qidiring..."/></div>
  {err&&<div className="alert errorBox">{err}</div>}
  <div className="tableCard"><div className="tableHead"><span>Mahsulot</span><span>Barcode</span><span>Sotuv narxi</span><span>Qoldiq</span></div>{items.length?items.map(p=><div className="tableRow" key={p.id}><span><b>{p.name}</b><small>Tannarx: {money(p.cost_price)}</small></span><span className="mono">{p.barcode||'—'}</span><span>{money(p.sale_price)}</span><span><b className={p.stock_qty<=p.min_stock_qty?'stockLow':''}>{p.stock_qty} dona</b><small>min: {p.min_stock_qty}</small></span></div>):<div className="emptyState"><b>Mahsulotlar hali yo‘q</b><span>Birinchi mahsulotni qo‘shing yoki barcode bilan kiriting.</span></div>}</div>
  {open&&<div className="modalBack" onMouseDown={()=>setOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalTitle"><div><b>Yangi mahsulot</b><span>Ombor va savdo uchun asosiy ma’lumotlar</span></div><button className="close" onClick={()=>setOpen(false)}>×</button></div><form className="form" onSubmit={submit}><div className="field"><label>Mahsulot nomi</label><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>Barcode</label><input value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})} placeholder="Skanerlang yoki yozing"/></div><div className="form2"><div className="field"><label>Kelish narxi</label><input type="number" min="0" value={form.cost_price} onChange={e=>setForm({...form,cost_price:e.target.value})} required/></div><div className="field"><label>Sotish narxi</label><input type="number" min="0" value={form.sale_price} onChange={e=>setForm({...form,sale_price:e.target.value})} required/></div></div><div className="form2"><div className="field"><label>Qoldiq</label><input type="number" min="0" value={form.stock_qty} onChange={e=>setForm({...form,stock_qty:e.target.value})} required/></div><div className="field"><label>Minimal qoldiq</label><input type="number" min="0" value={form.min_stock_qty} onChange={e=>setForm({...form,min_stock_qty:e.target.value})}/></div></div>{err&&<div className="error">{err}</div>}<button className="btn btnPrimary">Saqlash</button></form></div></div>}
 </AppShell>
}
